name: Charge
version: 3.1.2
description: Allows you to charge (one-time or subscription) your customer via Stripe
url: silentzconsulting.com/addons/charge
developer: Erin Dalzell
developer_url: silentzconsulting.com/addons
commercial: true
