fields:
  charge_formset:
    type: suggest
    mode: form
    display: Form
    max_items: 1
  charge_collections:
    type: suggest
    mode: collections
    display: Collections
  currency:
    type: text
    validate: required
    default: usd
