fields:
  charge_formset:
    type: suggest
    mode: form
    display: Form
    max_items: 1
  charge_collection:
    type: suggest
    mode: collections
    display: Collection
    max_items: 1
  offer_memberships:
   type: toggle
   display: Offer Paid Memberships?
   default: false
  currency:
    type: text
    validate: required
